<?php
   
return [
    'TAX_PERCENT' => 5,
    'CURRENCY' => 'AED',
    'is_active'=>[
        '0'=>[
            'label'=>'Dissable',
            'class'=>'bg-gradient-danger',
        ],
        '1'=>[
            'label'=>'Active',
            'class'=>'bg-gradient-success',
        ],
    ],
    'payment' => [
        'type'=>[
            '0'=>"Pay Later",
            '1'=>"Payment Link",
            '2'=>"Pay By Card",
            '3'=>"Cash Payment",
        ],
        'type_class'=>[
            '0'=>'bg-gradient-secondary',
            '1'=>'bg-gradient-info',
            '2'=>'bg-gradient-success',
            '3'=>'bg-gradient-primary',
        ],
        'icons'=>[
            '0'=>"fa-solid fa-basket-shopping",
            '1'=>"fa-solid fa-file-invoice-dollar",
            '2'=>"fa-solid fa-credit-card",
            '3'=>"fa-solid fa-money-bill-1",
        ],
        'text_class'=>[
            '0'=>'text-dark',
            '1'=>"text-danger",
            '2'=>"text-danger",
            '3'=>"text-info",
        ],
        'status'=>[
            '0'=>'Pending',
            '1'=>'Paid',
            '2'=>'Failed',
            '3'=>'Cancelled',
        ],
        'status_class'=>[
            '0'=>'bg-gradient-primary',
            '1'=>'bg-gradient-success',
            '2'=>'bg-gradient-danger',
            '3'=>'bg-gradient-danger',
        ],
        'status_icon'=>[
            '0'=>'fas fa-minus',
            '1'=>'fas fa-check',
            '2'=>'fas fa-minus',
            '3'=>'fas fa-minus',
        ],
        'status_icon_class'=>[
            '0'=>'btn-outline-danger',
            '1'=>'btn-outline-success',
            '2'=>'btn-outline-danger',
            '3'=>'btn-outline-danger',
        ],
        'status_update'=>[
            '1'=>'Paid',
            '2'=>'Failed',
            '3'=>'Cancelled',
        ],
    ],
    //Paymennt Section


    //Job Status
    'jobs'=>[
        'status' => [
            '0'=>'Start',
            '1'=>'Working Progress',
            '2'=>'Work Completed',
            '3'=>'Ready For Delivery',
            '4'=>'Delivered',
        ],
        'status_icon' => [
            '0'=>'fa-solid fa-hourglass-start',
            '1'=>'fa-solid fa-gear',
            '2'=>'fa-solid fa-recycle',
            '3'=>'fas fa-check',
            '4'=>'fa-solid fa-flag-checkered',
        ],
        'status_text_class' => [
            '0'=>'text-dark',
            '1'=>'text-danger',
            '2'=>'text-warning',
            '3'=>'text-info',
            '4'=>'text-success',
        ],
        'status_btn_class' => [
            '0'=>'bg-gradient-dark',
            '1'=>'bg-gradient-danger',
            '2'=>'bg-gradient-warning',
            '3'=>'bg-gradient-info',
            '4'=>'bg-gradient-success',
        ],
        'status_perc' => [
            '0'=>'25%',
            '1'=>'50%',
            '2'=>'75%',
            '3'=>'90%',
            '4'=>'100%',
        ],
        'status_perc_class' => [
            '0'=>'bg-gradient-dark',
            '1'=>'bg-gradient-danger',
            '2'=>'bg-gradient-warning',
            '3'=>'bg-gradient-info',
            '4'=>'bg-gradient-success',
        ],
        'job_status_bg' => [
            '0'=>'bg-gradient-dark',
            '1'=>'bg-gradient-danger',
            '2'=>'bg-gradient-warning',
            '3'=>'bg-gradient-info',
            '4'=>'bg-gradient-success',
        ],
    ],

    'job_status' => [
        '0'=>'Start',
        '1'=>'Working Progress',
        '2'=>'Completed',
        '3'=>'Ready For Delivery',
        '4'=>'Dispatched/Devlivered',
        '5'=>'Delivered',
    ],
    'job_status_icon' => [
        '0'=>'fa-solid fa-hourglass-start',
        '1'=>'fa-solid fa-gear',
        '2'=>'fa-solid fa-recycle',
        '3'=>'fas fa-check',
        '4'=>'fas fa-check',
        '5'=>'fa-solid fa-flag-checkered',
    ],
    'job_status_text_class' => [
        '0'=>'bg-gradient-danger',
        '1'=>'bg-gradient-primary',
        '2'=>'bg-gradient-primary',
        '3'=>'bg-gradient-info',
        '4'=>'bg-gradient-success',
        '5'=>'bg-gradient-success',
    ],
    'status_perc' => [
        '0'=>'25%',
        '1'=>'50%',
        '2'=>'75%',
        '3'=>'100%',
        '4'=>'100%',
    ],
    'status_perc_class' => [
        '0'=>'bg-gradient-default',
        '1'=>'bg-gradient-primary',
        '2'=>'bg-gradient-primary',
        '3'=>'bg-gradient-success',
        '4'=>'bg-gradient-success',
    ],

    'item_status'=>[
        '1'=>'Processing',
        '2'=>'Dispatch',
        '3'=>'Delivered'
    ],
    'item_status_text_class'=> [
        '1'=>'bg-gradient-info',
        '2'=>'bg-gradient-primary',
        '3'=>'bg-gradient-success',
    ],
    'job_department' => [
        '0'=>'Customer Service',
        '1'=>'Operation',
        '2'=>'Operation',
        '3'=>'Accounts',
        '4'=>'Finished'
    ],
    'job_department_text_class' => [
        '0'=>'text-danger',
        '1'=>'text-primary',
        '2'=>'text-info',
        '3'=>'text-success',
        '4'=>'text-success'
    ],
    
    'qr_status_color' => [
        '0'=>'linear-gradient(45deg, #f44336, #e91e63, #ff5722,#e91e63, #ff5722, #f44336, #e91e63,#ff5722, #ff9800)',
        '1'=>'linear-gradient(45deg, #f44336, #e91e63, #ff5722,#e91e63, #ff5722, #f44336, #e91e63,#ff5722, #ff9800)',
        '2'=>'linear-gradient(45deg, #f44336, #e91e63, #ff5722,#e91e63, #ff5722, #f44336, #e91e63,#ff5722, #ff9800)',
        '3'=>'linear-gradient(45deg, #009688, #4caf50, #cddc39,#0eb114, #009688, #009688, #4caf50, #cddc39,#0eb114, #009688)',
        '4'=>'linear-gradient(45deg, #009688, #4caf50, #cddc39,#0eb114, #009688, #009688, #4caf50, #cddc39,#0eb114, #009688)',
    ],
    'fuel' => [
        '1'=>'Quarter',
        '2'=>'Half',
        '3'=>'Full',
    ],
    "user_type" => [
        "1"=>"Administrator",
        "2"=>"Operation",
        "3"=>"Service",
        "4"=>"Sales",
        "5"=>"Finance",
        "6"=>"Security",
    ],
    "user_type_access"=>[
        "administrator"=>[
            "13"
        ],
        "operation"=>[
            "13","14","15","16"
        ],
        "finance"=>[
            "13","16"
        ],
    ],
    "sorting"=>[
        "1"=>"Latest",
        "2"=>"Oldest",
        "3"=>"Low Price",
        "4"=>"Hight Price",
    ],
    //'bhr-paymenkLink_payment_url'=>'https://bhr.ae/payment-app/api/pbl-payment-panel',
    'paymenkLink_payment_url'=>'http://172.23.25.95/gssapi/api/new-payment-link',
    
    'sms'=>[
        "1"=>[
            "name"=>"mshastra",
            "url"=>"https://mshastra.com/sendurlcomma.aspx",
            "sms_url"=>"https://mshastra.com/sendurlcomma.aspx?user=20092622&pwd=buhaleeba@123&senderid=BuhaleebaRE",
            "profileid"=>"20092622",
            "password"=>"buhaleeba@123",
            "senderid"=>"BuhaleebaRE",
        ]
    ],
    'country'=>[
        "AE"=>"United Arab Emirates",
        "SA"=>"Saudi Arabia",
        "OM"=>"Oman",
        "BH"=>"Bahrain",
        "KW"=>"Kuwait",
        "QA"=>"Qatar",
        "AF"=>"Afghanistan",
        "AL"=>"Albania",
        "DZ"=>"Algeria",
        "AS"=>"American Samoa",
        "AD"=>"Andorra",
        "AO"=>"Angola",
        "AI"=>"Anguilla",
        "AQ"=>"Antarctica",
        "AG"=>"Antigua and Barbuda",
        "AR"=>"Argentina",
        "AM"=>"Armenia",
        "AW"=>"Aruba",
        "AU"=>"Australia",
        "AT"=>"Austria",
        "AZ"=>"Azerbaijan",
        "BS"=>"Bahama",
        "BD"=>"Bangladesh",
        "BB"=>"Barbados",
        "BY"=>"Belarus",
        "BE"=>"Belgium",
        "BZ"=>"Belize",
        "BJ"=>"Benin",
        "BM"=>"Bermuda",
        "BT"=>"Bhutan",
        "BO"=>"Bolivia",
        "BA"=>"Bosnia and Herzegovina",
        "BW"=>"Botswana",
        "BV"=>"Bouvet Island",
        "BR"=>"Brazil",
        "BN"=>"Brunei Darussalam",
        "BG"=>"Bulgaria",
        "BF"=>"Burkina Faso",
        "BI"=>"Burundi",
        "KH"=>"Cambodia",
        "CM"=>"Cameroon",
        "CA"=>"Canada",
        "CV"=>"Cape Verde",
        "KY"=>"Cayman Islands",
        "CF"=>"Central African Republic",
        "TD"=>"Chad",
        "CL"=>"Chile",
        "CN"=>"China",
        "CX"=>"Christmas Island",
        "CC"=>"Cocos (Keeling) Islands",
        "CO"=>"Colombia",
        "KM"=>"Comoros",
        "CG"=>"Congo",
        "CK"=>"Cook Islands",
        "CR"=>"Costa Rica",
        "CI"=>"Cote D'Ivoire (Ivory Coast)",
        "HR"=>"Croatia",
        "CU"=>"Cuba",
        "CY"=>"Cyprus",
        "CZ"=>"Czech Republic",
        "DK"=>"Denmark",
        "DJ"=>"Djibouti",
        "DM"=>"Dominica",
        "DO"=>"Dominican Republic",
        "TP"=>"East Timor",
        "EC"=>"Ecuador",
        "EG"=>"Egypt",
        "SV"=>"El Salvador",
        "GQ"=>"Equatorial Guinea",
        "ER"=>"Eritrea",
        "EE"=>"Estonia",
        "ET"=>"Ethiopia",
        "FO"=>"Faroe Islands",
        "FJ"=>"Fiji",
        "FI"=>"Finland",
        "FR"=>"France",
        "GA"=>"Gabon",
        "GM"=>"Gambia",
        "GE"=>"Georgia",
        "DE"=>"Germany",
        "GH"=>"Ghana",
        "GR"=>"Greece",
        "GL"=>"Greenland",
        "GD"=>"Grenada",
        "GP"=>"Guadeloupe",
        "GU"=>"Guam",
        "GT"=>"Guatemala",
        "GN"=>"Guinea",
        "GW"=>"Guinea-Bissau",
        "GY"=>"Guyana",
        "HT"=>"Haiti",
        "VA"=>"Holy See (Vatican City State)",
        "HN"=>"Honduras",
        "HU"=>"Hungary",
        "IS"=>"Iceland",
        "IN"=>"India",
        "ID"=>"Indonesia",
        "IQ"=>"Iraq",
        "IE"=>"Ireland",
        "IR"=>"Islamic Republic of Iran",
        "IL"=>"Israel",
        "IT"=>"Italy",
        "JM"=>"Jamaica",
        "JP"=>"Japan",
        "JO"=>"Jordan",
        "KZ"=>"Kazakhstan",
        "KE"=>"Kenya",
        "KI"=>"Kiribati",
        "KG"=>"Kyrgyzstan",
        "LA"=>"Lao People's Democratic Republic",
        "LV"=>"Latvia",
        "LB"=>"Lebanon",
        "LS"=>"Lesotho",
        "LR"=>"Liberia",
        "LY"=>"Libyan Arab Jamahiriya",
        "LI"=>"Liechtenstein",
        "LT"=>"Lithuania",
        "LU"=>"Luxembourg",
        "MK"=>"Macedonia",
        "MG"=>"Madagascar",
        "MW"=>"Malawi",
        "MY"=>"Malaysia",
        "MV"=>"Maldives",
        "ML"=>"Mali",
        "MT"=>"Malta",
        "MH"=>"Marshall Islands",
        "MQ"=>"Martinique",
        "MR"=>"Mauritania",
        "MU"=>"Mauritius",
        "YT"=>"Mayotte",
        "MX"=>"Mexico",
        "FM"=>"Micronesia",
        "MD"=>"Moldova, Republic of",
        "MC"=>"Monaco",
        "MN"=>"Mongolia",
        "ME"=>"Montenegro",
        "MA"=>"Morocco",
        "MZ"=>"Mozambique",
        "MM"=>"Myanmar",
        "NA"=>"Namibia",
        "NR"=>"Nauru",
        "NP"=>"Nepal",
        "NL"=>"Netherlands",
        "AN"=>"Netherlands Antilles",
        "NC"=>"New Caledonia",
        "NZ"=>"New Zealand",
        "NI"=>"Nicaragua",
        "NE"=>"Niger",
        "NG"=>"Nigeria",
        "NU"=>"Niue",
        "KP"=>"North Korea",
        "MP"=>"Northern Mariana Islands",
        "NO"=>"Norway",
        "XX"=>"Others",
        "PK"=>"Pakistan",
        "PW"=>"Palau",
        "PS"=>"Palestine",
        "PA"=>"Panama",
        "PG"=>"Papua New Guinea",
        "PY"=>"Paraguay",
        "PE"=>"Peru",
        "PH"=>"Philippines",
        "PN"=>"Pitcairn",
        "PL"=>"Poland",
        "PF"=>"Polynesia (French)",
        "PT"=>"Portugal",
        "PR"=>"Puerto Rico",
        "RM"=>"Republic of Myanmar",
        "KR"=>"Republic of South Korea",
        "RE"=>"Reunion",
        "RO"=>"Romania",
        "RU"=>"Russian Federation",
        "RW"=>"Rwanda",
        "LC"=>"Saint Lucia",
        "MF"=>"Saint Martin",
        "PM"=>"Saint Pierre and Miquelon",
        "WS"=>"Samoa",
        "SM"=>"San Marino",
        "ST"=>"Sao Tome and Principe",
        "SN"=>"Senegal",
        "RS"=>"Serbia",
        "SC"=>"Seychelles",
        "SL"=>"Sierra Leone",
        "SG"=>"Singapore",
        "SK"=>"Slovakia",
        "SI"=>"Slovenia",
        "SB"=>"Solomon Islands",
        "SO"=>"Somalia",
        "ZA"=>"South Africa",
        "ES"=>"Spain",
        "LK"=>"Sri Lanka",
        "SH"=>"St. Helena",
        "KN"=>"St. Kitts and Nevis",
        "VC"=>"St. Vincent and the Grenadines",
        "SD"=>"Sudan",
        "SR"=>"Suriname",
        "SJ"=>"Svalbard and Jan Mayen Islands",
        "SZ"=>"Swaziland",
        "SE"=>"Sweden",
        "CH"=>"Switzerland",
        "SY"=>"Syrian Arab Republic",
        "TW"=>"Taiwan, Province of China",
        "TJ"=>"Tajikistan",
        "TH"=>"Thailand",
        "YU"=>"The former Yugoslav Republic of Macedonia",
        "TG"=>"Togo",
        "TK"=>"Tokelau",
        "TO"=>"Tonga",
        "TT"=>"Trinidad and Tobago",
        "TN"=>"Tunisia",
        "TR"=>"Turkey",
        "TM"=>"Turkmenistan",
        "TC"=>"Turks and Caicos Islands",
        "TV"=>"Tuvalu",
        "UG"=>"Uganda",
        "UA"=>"Ukraine",
        "UK"=>"United Kingdom",
        "TZ"=>"United Republic of Tanzania",
        "US"=>"United States of America",
        "UY"=>"Uruguay",
        "UZ"=>"Uzbekistan",
        "VU"=>"Vanuatu",
        "VE"=>"Venezuela",
        "VN"=>"Vietnam",
        "VI"=>"Virgin Islands (USA)",
        "WF"=>"Wallis and Futuna Islands",
        "EH"=>"Western Sahara",
        "YE"=>"Yemen",
        "ZR"=>"Zaire",
        "ZM"=>"Zambia",
        "ZW"=>"Zimbabwe",
    ]

]
  
?>